# action.yml
name: 'ansible-inventory-diff'
description: 'Determines the difference in inventory variables between two git refs'
branding:
  icon: info
  color: blue
inputs:
  base-ref:
    description: 'Base git reference of comparison'
    required: false
    default: 'origin/main'
outputs:
  result:
    description: 'full output of ansible-inventory-diff'
  snippet:
    description:
      lines of result before truncation (or entire result if shorter),
      suitable for a github comment
  truncate:
    default: 200
    required: false
    description:
      Maximum number of lines taken from result to create snippet
runs:
  using: 'docker'
  image: docker://quay.io/skedulo/ansible-inventory-diff:v1.5-rc11-1-ga97eeb6
  entrypoint: '/bin/action.sh'
  args:
    - ${{ inputs.base-ref }}
    - ${{ inputs.truncate }}
