# action.yml
name: 'ansible-inventory-diff'
description: 'Determines the difference in inventory variables between two git refs'
branding:
  icon: info
  color: blue
inputs:
  base-ref:  # id of input
    description: 'Base git reference of comparison'
    required: true
    default: 'origin/main'
outputs:
  result: # id of output
    description: 'output of ansible-inventory-diff'
runs:
  using: 'docker'
  image: docker://quay.io/skedulo/ansible-inventory-diff:v1.5-rc4-3-g177a20e
  entrypoint: '/bin/action.sh'
  args:
    - ${{ inputs.base-ref }}
